batch_size: 64
height: 45
learning_rate: 0.001
max_text_length: 4
model_path: Models/02_captcha_to_text\202408281655
train_epochs: 1000
train_workers: 20
vocab: HOURNLTV35AX10ZY6SB4MPJ9E2WC8K7GFQ
width: 156
